### ISSUE TITLE
How to create / download synthetic digits dataset?

### ISSUE THREAD

**Issue by engharat** [pumpikano/tf-dann#15]
Hi,
I'm trying to reproduce some DA results using the synthetic digits dataset (not mnist-M one).
According to this paper:
https://vision.in.tum.de/_media/spezial/bib/haeusser_iccv_17.pdf
the synthetic digits -> MNIST experiment run on a synthetic digits dataset provided by you.
The same dataset seems to be used by you in your "Domain-Adversarial Training of Neural Networks" work, and this synth dataset is mentioned in this github repo README:
"The MNIST-DANN.ipynb recreates the MNIST experiment from the papers on a synthetic dataset"
But it seems I cannot find proper code for generating it or download it ( I would like to get the very same dataset for fair comparison).
I thank you in advance!

**Comment by pumpikano** [comment]
The only synthetic dataset used in this repo is MNIST-M and the that dataset is built by `create_mnistm.py`. The authors of that paper have used my code to generate MNIST-M, with some small modifications: https://github.com/haeusser/learning_by_association/blob/master/semisup/tools/data_util/create_mnistm.py

Since you say you *don't* mean MNIST-M, are you talking about the Synth → SVHN experiment from that paper? On page 4, the authors say that they obtained the Synthetic Digits dataset from the authors of [9]. I am not an author of that paper, so perhaps you should reach out to them to access that dataset.

**Comment by engharat** [comment]
Very thanks for the support. Yes, I'm talking about Synth -> SVHN experiment;  I will contact the authors.

**Comment by MLEnthusiast** [comment]
@engharat Did you manage to get hold of the synthetic digits data set?

**Comment by engharat** [comment]
> @engharat Did you manage to get hold of the synthetic digits data set?

@MLEnthusiast I managed to get it some months ago, I have uploaded it for you at the following link but double check its content as I'm not 100% sure it is exactly the same dataset.
[https://drive.google.com/open?id=1lQoeTViThmv79AiY6tgibnPItl5y6zUc](url)

**Comment by MLEnthusiast** [comment]
Thank you @engharat
